name: Auto Build Termux App
on: 
   workflow_dispatch:
     branches: [ master ]
   repository_dispatch:
    types: start auto build Termux
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      run: git clone https://github.com/termux/termux-app ./
    - name: Build
      run: |
        bash test.sh
        echo "::set-env name=zt::$?"
    - name: Upload Apk To Lzy
      if: env.zt == 0
      run: |
        ${{secrets.LZY_UPDATE}}
        up_lzy Termux_app_*.apk
    - name: Store generated APK file
      if: env.zt == 0
      uses: actions/upload-artifact@v1
      with:
        name: termux-app
        path: ./app/build/outputs/apk/debug/app-debug.apk
