name: Auto Build Termux Api Apk
on: 
   workflow_dispatch:
   repository_dispatch:
    types: start auto build Api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 拉取源代码
      run: git clone https://github.com/termux/termux-api ./
    - name: Build
      run: |
        local_version=$(curl -s "http://api.funs.ml/lzy_dir/api.php?fdir=b0evwprqb" |grep " Termux_api_" |head -1 |awk -F "api_" '{print $2}' |awk -F ".apk" '{print $1}')
        remote_version=$(cat app/build.gradle |grep "versionName \"" |awk -F "\"" '{print $2}')
        echo "已编译版本--$local_version"
        echo "官方最新版本--$remote_version"
        if [ "$local_version" == "$remote_version" ];then
          echo "无最新版本!"
          exit 1;
        fi
        echo "::set-env name=zt::$?"
        printf "开始编译\n"
        ./gradlew assembleDebug
        cp app/build/outputs/apk/debug/app-debug.apk ./Termux_api_${remote_version}.apk
        echo "编译结束"
    - name: Upload Apk To Lzy
      if: env.zt == 0
      run: |
        ${{secrets.LZY_UPDATE}}
        up_lzy Termux_api_*.apk
    - name: Store generated APK file
      if: env.zt == 0
      uses: actions/upload-artifact@v1
      with:
        name: termux-api
        path: ./app/build/outputs/apk/debug/app-debug.apk
