name: Auto Build Curl
on: 
   workflow_dispatch:
   repository_dispatch:
    types: start auto build Curl
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 拉取源代码
      run: git clone https://github.com/curl/curl ./
    - name: Build
      run: |
        ls
        cmake -static -pthread -lrt -ldl
        

