name: Auto Build Curl
on: 
   workflow_dispatch:
   repository_dispatch:
    types: start auto build Curl
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 拉取源代码
      run: |
        wget "https://curl.haxx.se/download/curl-7.72.0.tar.xz"
        tar pxvf curl-7.72.0.tar.xz
    - name: Build
      run: |
        cd curl-7.72.0
        pwd
        ls
        ./configure --prefix=/home/runner/work/Auto-Build/Auto-Build/curl-7.72.0 --disable-shared --enable-static --without-libidn --without-ssl --without-librtmp --without-gnutls --without-nss --without-libssh2 --without-zlib --without-winidn --disable-rtsp --disable-ldap --disable-ldaps --disable-ipv6
        make
        mkdir bin
        make install
        echo "成功"
        ls
        ls bin/
    - name: Store generated APK file
      uses: actions/upload-artifact@v1
      with:
        name: curl
        path: ./curl-7.72.0/bin/curl

